# TODO
# general settings
name: PartFormer_x3
model_type: DATModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X3_sub.lmdb
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb
      # (for lmdb)
      # type: lmdb

    gt_size: 192
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/GTmod12
    dataroot_lq: datasets/Set5/LRbicx3
    io_backend:
      type: disk

  val_2:
    name: val_set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/GTmod12
    dataroot_lq: datasets/Set14/LRbicx3
    io_backend:
      type: disk

  # val_3:
  #   name: manga109
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/Manga109/GTmod12
  #   dataroot_lq: datasets/Manga109/LRbicx2
  #   #filename_tmpl: '{}x2'
  #   io_backend:
  #     type: disk

  # val_4:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/Urban100/GTmod12
  #   dataroot_lq: datasets/Urban100/LR_bicubic/X2
  #   # filename_tmpl: '{}x4'
  #   io_backend:
  #     type: disk

  val_5:
    name: BSD100
    type: PairedImageDataset
    dataroot_gt: datasets/BSD100/GTmod12
    dataroot_lq: datasets/BSD100/LRbicx3
    # filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
network_g:
  type: PART
  upscale: 3
  in_chans: 3
  img_size: 64
  img_range: 1.
  depth: [19]
  embed_dim: 96
  num_heads: [2]
  expansion_factor: 2
  resi_connection: '3conv'
  split_size: [8,32]
  upsampler: 'pixelshuffledirect'


# path
path:
  pretrain_network_g: experiments/PartFormer_x2_abla_new/models/net_g_latest.pth
  strict_load_g: false
  resume_state:

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  fre_opt:
    type: FrequencyLoss
    loss_weight: !!float 1e-1

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
