# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: PartFormer-Gauss-color
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  # train:
  #   name: TrainSet
  #   type: Dataset_GaussianDenoising
  #   sigma_type: random
  #   sigma_range: [0,50]
  #   in_ch: 3    ## RGB image
  #   dataroot_gt: ./dataset/DFWB
  #   dataroot_lq: none
  #   geometric_augs: true

  #   filename_tmpl: '{}'
  #   io_backend:
  #     type: disk

  train:
    task: denoising_color
    noise: 15 # 15/25/50
    name: DFWB_RGB
    type: PairedImageDataset_gass
    sigma_type: random
    sigma_range: [0,50]
    dataroot_gt: ./dataset/DFWB
    dataroot_lq: ./dataset/DFWB
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    task: denoising_color
    sigma_type: constant
    sigma_range: 15
    name: McMaster
    type: PairedImageDataset_gass
    dataroot_gt: ./datasets/Denoisy/McMaster
    dataroot_lq: ./datasets/Denoisy/McMaster
    filename_tmpl: '{}'
    io_backend:
      type: disk

network_g:
  type: PART
  in_chans: 3
  img_size: 128
  img_range: 1.
  depth: [19]
  embed_dim: 96
  num_heads: [2]
  expansion_factor: 2
  resi_connection: '3conv'
  split_size: [8,32]

# path
path:
  pretrain_network_g: 
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean
  fre_opt:
    type: FrequencyLoss
    loss_weight: !!float 1e-1

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
